# Generated by Django 3.2.4 on 2021-07-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=68)),
                ('title', models.CharField(max_length=68)),
                ('reviews', models.TextField(max_length=564)),
                ('alias', models.CharField(max_length=68)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CommentReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(max_length=564)),
                ('Title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.reviews')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
