# Generated by Django 3.2.4 on 2021-07-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='img_url',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='alias',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='productname',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviews',
            field=models.TextField(max_length=564),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(max_length=68),
        ),
        migrations.CreateModel(
            name='CommentReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=68)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(max_length=564)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.reviews')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
