from django import forms
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        """
        placerholders and classes, remove autogenerated labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placerholders = {
            'default_phone_number': 'Phone number',
            'default_street_adress': 'Street Adress',
            'default_delivery_adress': 'Delivery Adress',
            'default_town_or_city': 'Town or City',
            'default_postcode': 'Postal code',
            'default_county': 'County, State or Locality',
            }

        self.fields['default_phone_number'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'default_country':
                if self.fields[field].required:
                    placeholder = f'{placerholders[field]}*'
                else:
                    placeholder = placerholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
                self.fields[field].widget.attrs['class'] = 'stripe-style-input'
                self.fields[field].label = False
