from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('full_name', 'email', 'phone_number', 'country', 'postcode', 'town_or_city', 'street_adress', 'delivery_adress', 'county',)

    def __init__(self, *args, **kwargs):
        """
        placerholders and classes, remove autogenerated labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placerholders = {
            'full_name': 'Full Name',
            'email': 'Email',
            'phone_number': 'Phone number',
            'street_adress': 'Street Adress',
            'delivery_adress': 'Delivery Adress',
            'town_or_city': 'Town or City',
            'postcode': 'Postal code',
            'country': 'Country',
            'county': 'County',
            }

        self.fields['full_name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if self.fields[field].required:
                placeholder = f'{placerholders[field]}*'
            else:
                placeholder = placerholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].label = False
